spring:
  application:
    name: freshly-backend
  profiles:
    active: ${SPRING_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:50MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,metrics,info}
  endpoint:
    info:
      access: READ_ONLY
    health:
      access: READ_ONLY
    metrics:
      access: READ_ONLY

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/