spring:
  application:
    name: freshly-backend

  docker:
    compose:
      enabled: false

  mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTH_DATABASE:admin}
    representation:
      uuid: STANDARD

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      email-verification: ${JWT_EXPIRATION_EMAIL_VERIFICATION:86400000}
      password-reset: ${JWT_EXPIRATION_PASSWORD_RESET:3600000}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:1800000}
      cookie-name: "refresh_token"
    cookie:
      httpOnly: true
      secure: true
      sameSite: Strict
      path: "/"

external-service:
  gios:
    api-url: ${EXTERNAL_SERVICE_GIOS_API_URL:https://api.gios.gov.pl/pjp-api/v1/rest}

application:
  file:
    uploads:
      file-output-path: ${FILE_UPLOAD_PATH:/var/app/uploads}

  frontend:
    url: ${FRONTEND_URL}

  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL}
    realm: ${KEYCLOAK_REALM}
    admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    admin-username: ${KEYCLOAK_ADMIN_USERNAME}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
    user-client-id: ${KEYCLOAK_USER_CLIENT_ID}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: WARN
    com.vertyll.freshly: INFO
    org.springframework.security: INFO
    org.springframework.mail: INFO